use orders;
SELECT 
    product_id, product_price
FROM
    product
WHERE
    product_id < 1000
        AND product_price IN (SELECT 
            product_price
        FROM
            product
        GROUP BY product_price
        HAVING COUNT(product_price) > 1);

SELECT 
    PC.PRODUCT_CLASS_DESC, SUM(OI.PRODUCT_QUANTITY)
FROM
    PRODUCT P
        NATURAL JOIN
    ADDRESS A
        NATURAL JOIN
    ONLINE_CUSTOMER OC
        NATURAL JOIN
    ORDER_HEADER OH
        NATURAL JOIN
    ORDER_ITEMS OI
        NATURAL JOIN
    PRODUCT_CLASS PC
GROUP BY PC.PRODUCT_CLASS_DESC
HAVING A.COUNTRY <> 'INDIA';

SELECT ALL
    OH.CUSTOMER_ID,
    OC.CUSTOMER_FNAME,
    A.ADDRESS_LINE2,
    SUM(OI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) AS TOTAL_SALES
FROM
    ADDRESS A
        NATURAL JOIN
    ONLINE_CUSTOMER OC
        NATURAL JOIN
    ORDER_HEADER OH
        NATURAL JOIN
    ORDER_ITEMS OI
        NATURAL JOIN
    PRODUCT P
WHERE
    A.ADDRESS_LINE2 IN (SELECT 
            ADDRESS_LINE2
        FROM
            ADDRESS
        WHERE
            ADDRESS_LINE2 = CITY)
GROUP BY OH.CUSTOMER_ID;

SELECT 
    OI.PRODUCT_ID,
    P.PRODUCT_DESC,
    SUM(OI.PRODUCT_QUANTITY) AS TOTAL_QUANTITY
FROM
    ORDER_ITEMS OI
        NATURAL JOIN
    PRODUCT P
GROUP BY OI.PRODUCT_ID
HAVING OI.PRODUCT_ID IN (SELECT 
        PRODUCT_ID
    FROM
        ORDER_ITEMS
    WHERE
        PRODUCT_ID = 201);

SELECT 
    MONTH(OH.ORDER_SHIPMENT_DATE), SUM(OI.PRODUCT_QUANTITY)
FROM
    ORDER_ITEMS OI
        NATURAL JOIN
    ORDER_HEADER OH
        NATURAL JOIN
    ONLINE_CUSTOMER OC
        NATURAL JOIN
    ADDRESS AD
GROUP BY MONTH(OH.ORDER_SHIPMENT_DATE)
HAVING AD.COUNTRY IN (SELECT 
        COUNTRY
    FROM
        ADDRESS
    WHERE
        COUNTRY NOT LIKE 'INDIA');

SELECT 
    OC.CUSTOMER_ID,
    OC.CUSTOMER_FNAME,
    OC.CUSTOMER_LNAME,
    SUM(OI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) AS TOTAL_VALUE
FROM
    ONLINE_CUSTOMER OC
        NATURAL JOIN
    ORDER_HEADER OH
        NATURAL JOIN
    ORDER_ITEMS OI
        NATURAL JOIN
    PRODUCT P
GROUP BY OC.CUSTOMER_ID
HAVING OC.CUSTOMER_ID IN (SELECT 
        OC.CUSTOMER_ID
    FROM
        ONLINE_CUSTOMER OC
            NATURAL JOIN
        ORDER_HEADER OH
            NATURAL JOIN
        ORDER_ITEMS OI
            NATURAL JOIN
        PRODUCT P
    WHERE
        (OI.PRODUCT_QUANTITY * P.PRODUCT_PRICE) > 10000)
ORDER BY TOTAL_VALUE DESC
LIMIT 0 , 1;

SELECT 
    PC.PRODUCT_CLASS_CODE,
    PC.PRODUCT_CLASS_DESC,
    SUM(P.PRODUCT_PRICE) AS VAL
FROM
    PRODUCT_CLASS PC
        NATURAL JOIN
    PRODUCT P
GROUP BY PC.PRODUCT_CLASS_CODE
ORDER BY VAL DESC
LIMIT 0 , 1;

SELECT 
    OH.SHIPPER_ID,
    S.SHIPPER_NAME,
    SUM(P.LEN * P.WIDTH * P.HEIGHT) AS VOLUME
FROM
    SHIPPER S
        NATURAL JOIN
    ORDER_HEADER OH
        NATURAL JOIN
    ORDER_ITEMS
        NATURAL JOIN
    PRODUCT P
GROUP BY SHIPPER_ID
ORDER BY VOLUME DESC
LIMIT 0 , 1;

SELECT 
    OH.CUSTOMER_ID, SUM(C.LEN * C.WIDTH * C.HEIGHT) AS VOLUME
FROM
    CARTON C
        NATURAL JOIN
    ORDER_HEADER OH
GROUP BY OH.CUSTOMER_ID;

SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_DESC,
    SUM(OI.PRODUCT_QUANTITY) AS TOTAL_QUANTITY
FROM
    PRODUCT P
        NATURAL JOIN
    ORDER_ITEMS OI
GROUP BY PRODUCT_ID
ORDER BY TOTAL_QUANTITY DESC
LIMIT 0 , 1;

SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_DESC,
    SUM(OI.PRODUCT_QUANTITY) AS TOTAL_QUANTITY
FROM
    PRODUCT P
        NATURAL JOIN
    ORDER_ITEMS OI
GROUP BY PRODUCT_ID
ORDER BY TOTAL_QUANTITY ASC
LIMIT 0 , 1;